### ISSUE TITLE
Web Map Application: Calculate area of polygon?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/MapSAROnline#3]
"Also is it possible for ArcGIS Online to automatically calculate the area of a polygon when it
is created and put that value in a attribute table field?  I have this feature in IGT4SAR and I believe it is also in MapSAR and it is really nice to have when estimating resource needs and estimated time on
task. "

**Comment by pjdohertygis** [comment]
@driskull - is there a widget for Web App Builder that calculates area for a polygon during / after it is drawn?

**Comment by driskull** [comment]
not that I know of. maybe measurement could do it?

**Comment by jpedder** [comment]
In desktop this is usually accomplished through a script of attribute assistant. In AGOl you'd need to create a widget to populate the field value, if you just need the area use the measure tool.

**Comment by pjdohertygis** [comment]
I think Don @dferguso was referring to the capability to see the area being
drawn on the fly or at least when the polygon is saved. Then the area is
added to the attribute table so we know how large the area is. It is great
functionality in the desktop, but probably pretty unlikely to be developed
for WebApp builder.

I will close the issue.

**Comment by pjdohertygis** [comment]
Resolved - you can use Arcade https://developers.arcgis.com/arcade/function-reference/geometry_functions/ - this has been included in the Learn Lesson https://learn.arcgis.com/en/projects/prepare-for-search-and-rescue-incidents/lessons/create-a-map.htm#ESRI_SECTION1_D3272DE5B74B4F159B09A4AAC2BAA66A

**Comment by pjdohertygis** [comment]
Resolved! https://learn.arcgis.com/en/projects/prepare-for-search-and-rescue-incidents/lessons/create-a-map.htm#ESRI_SECTION1_D3272DE5B74B4F159B09A4AAC2BAA66A
